"""Generates src/woe-blacklist.js from Arcadia's pre-trans WoE item blacklist:
https://gitlab.com/arcadia-online/arcadia-online/-/blob/master/changelogs/attachments/pre-trans-woe-item-blacklist.md

    python tools/update_woe_blacklist.py
"""

import json
import re
import urllib.request
from pathlib import Path

URL = "https://gitlab.com/arcadia-online/arcadia-online/-/raw/master/changelogs/attachments/pre-trans-woe-item-blacklist.md"
OUT = Path(__file__).resolve().parent.parent / "src" / "woe-blacklist.js"

# Own additions on top of Arcadia's list, kept on every update: [name, slots, item id].
EXTRA = [
    ["Valkyrian Manteau", 1, 2524],
]


def main():
    req = urllib.request.Request(URL, headers={"User-Agent": "Mozilla/5.0 (ArcadiaArmory blacklist update)"})
    with urllib.request.urlopen(req) as r:
        text = r.read().decode("utf-8")
    stand = (re.search(r"as of (\d{4}-\d{2}-\d{2})", text) or [None, "?"])[1]
    # "- Zweihander [2] (1171)" -> ["Zweihander", 2, 1171]
    rows = []
    for line in text.splitlines():
        m = re.match(r"^- (.+?)(?: \[(\d)\])? \((\d+)\)\s*$", line)
        if m:
            rows.append([m.group(1), int(m.group(2) or 0), int(m.group(3))])
    known = {r[2] for r in rows}
    extra = [r for r in EXTRA if r[2] not in known]
    rows += extra
    OUT.write_text(
        "// Generated by tools/update_woe_blacklist.py - do not edit by hand.\n"
        f"// Items disabled in pre-trans WoE (list as of {stand}): [name, slots, item id].\n"
        f"// Plus {len(extra)} own addition(s) from EXTRA in the script.\n"
        f"window.__AA_WOE_BLACKLIST = {json.dumps({'asOf': stand, 'items': rows}, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}: {len(rows)} items (as of {stand}, {len(extra)} own additions)")


if __name__ == "__main__":
    main()
