"""Generates src/headgear-slots.js: headgears that occupy more than one head slot
(e.g. Mythical Lion Mask = upper + middle, Sphinx Hat = upper + lower).

The calculator lists every headgear under a single slot only, so this comes
from the public item database of the Arcadia control panel (all "Armor" pages,
column "Equip Locations").

    python tools/update_headgear_slots.py
"""

import json
import re
import urllib.request
from html.parser import HTMLParser
from pathlib import Path

BASE = "https://cp.arcadia-online.org/item/?type=5&equip_loc=-1&p={}"
OUT = Path(__file__).resolve().parent.parent / "src" / "headgear-slots.js"

UPPER, MIDDLE, LOWER = 256, 512, 1
NAMED = {
    "upper headgear": UPPER,
    "middle headgear": MIDDLE,
    "lower headgear": LOWER,
    "upper/mid headgear": UPPER | MIDDLE,
    "upper/mid/lower headgear": UPPER | MIDDLE | LOWER,
    "mid/lower headgear": MIDDLE | LOWER,
}


class Rows(HTMLParser):
    """Collects the text of every <td> per <tr> inside <tbody>."""

    def __init__(self):
        super().__init__()
        self.rows, self.row, self.cell, self.in_body = [], None, None, False

    def handle_starttag(self, tag, attrs):
        if tag == "tbody":
            self.in_body = True
        elif tag == "tr" and self.in_body:
            self.row = []
        elif tag == "td" and self.row is not None:
            if self.cell is not None:  # the name cell is not closed in the panel's HTML
                self.handle_endtag("td")
            self.cell = []

    def handle_endtag(self, tag):
        if tag == "td" and self.cell is not None:
            self.row.append(" ".join("".join(self.cell).split()))
            self.cell = None
        elif tag == "tr" and self.row is not None:
            self.rows.append(self.row)
            self.row = None
        elif tag == "tbody":
            self.in_body = False

    def handle_data(self, data):
        if self.cell is not None:
            self.cell.append(data)


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (ArcadiaArmory headgear update)"})
    with urllib.request.urlopen(req) as r:
        return r.read().decode("utf-8", "replace")


def location_mask(text):
    t = text.strip().lower()
    if t in NAMED:
        return NAMED[t]
    m = re.fullmatch(r"\((\d+)\)", t)  # unnamed combinations are shown as "(257)"
    return int(m.group(1)) if m else 0


def main():
    items, seen = [], set()
    for page in range(1, 200):
        parser = Rows()
        parser.feed(fetch(BASE.format(page)))
        rows = [r for r in parser.rows if len(r) >= 11 and r[0].isdigit()]
        new = [r for r in rows if r[0] not in seen]
        if not new:
            break
        for r in new:
            seen.add(r[0])
            mask = location_mask(r[3]) & (UPPER | MIDDLE | LOWER)
            if bin(mask).count("1") < 2:
                continue
            name = re.sub(r"\s*\[\d\]\s*$", "", r[1])
            slots = int(r[10]) if r[10].isdigit() else 0
            items.append([name, slots, int(r[0]), mask])
    OUT.write_text(
        "// Generated by tools/update_headgear_slots.py - do not edit by hand.\n"
        "// Headgears occupying several head slots: [name, slots, item id, mask]\n"
        "// with mask bits upper = 256, middle = 512, lower = 1.\n"
        f"window.__AA_HEADGEAR_SLOTS = {json.dumps(items, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT}: {len(items)} multi-slot headgears from {len(seen)} armor items")


if __name__ == "__main__":
    main()
